spring:
  data:
    mongodb:
      uri: "mongodb+srv://bluewlsghks:LAqDNrqj6WMZsKGo@leeandcha.nyoldck.mongodb.net/LEECHA_MESSENGER?retryWrites=true&w=majority&appName=LEEandCHA"
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
